### PR TITLE
Add Pinch Gestures

### PR DESCRIPTION
**Pull request by mmhobi7**
https://github.com/Hikari9/comfortable-swipe-ubuntu/issues/8
2 Finger pinch support can be added by adding a corresponding value to mask

### CODE REVIEW

**Comment by mmhobi7** [comment]
`xdotool key super+w ` sometimes displays the dash when closing the spread. I think it's a race condition in xdotool and unity.

**Comment by Hikari9** [comment]
What is the difference between the pinch directions (up/down/left/right) for the 3- and 4-finger pinch?

By the way, I appreciate your effort for your contribution.

**Comment by mmhobi7** [comment]
It’s based off where the pinch is pulled towards on the touchpad I think, there’s an extra x.xx @ x.xx added to the end of the pinch updated like in libinput and I don’t know what it is.

**Comment by Hikari9** [comment]
Hello @Aaahh , closing this PR since this is outdated; file structure has been drastically changed as of commit e2e534ea2fb9b731dbd5c27dbff559464c4d2d13 (see Pull Request #41).

If you want to push through with this feature, kindly make a new pull request incorporating your new changes. Thanks!

**Pull request closed without merging**
